# Generated by Django 4.0 on 2022-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_product_fat_alter_product_kcal_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='favorites',
            field=models.ManyToManyField(to='main_site.Product'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
