# Generated by Django 4.0 on 2022-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_product_fat_alter_product_kcal_and_more'),
        ('user_management', '0004_remove_userextension_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='favorites',
            field=models.ManyToManyField(to='main_site.Product'),
        ),
    ]
