# Generated by Django 4.0 on 2022-01-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_userextension_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='favorites',
        ),
    ]
