# Generated by Django 4.1.2 on 2022-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_remove_userextension_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
