# Generated by Django 4.0 on 2022-01-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_product_fat_product_kcal_product_protein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.IntegerField(),
        ),
    ]
